### ISSUE TITLE
Couldn't network stream

### ISSUE THREAD

**Issue by HongSic** [ioctlLR/NVorbis#17] opened 2019-01-08 08:45 UTC
or If available solving this problem, teach me.
`            

            FileStream fs = new FileStream("D:\\test.raw", FileMode.Create);
            WebRequest webRequest = (HttpWebRequest)WebRequest.Create("http://theprodigy.ru:8000/live.ogg");
            WebResponse resp = webRequest.GetResponse();
            VorbisReader vorbis = new VorbisReader(resp.GetResponseStream(), true); //System.NotSupportedException

            long testlen = 0;
            while (testlen < 100000)
            {
                float[] buf = new float[1024];
                int len = vorbis.ReadSamples(buf, 0, buf.Length);
                for (int i = 0; i < len; i++)
                {
                    byte[] four = BitConverter.GetBytes(buf[i]);
                    fs.Write(four, 0, 4);
                }

                fs.Flush();
            }
`

**Comment by ToddBertaOldham** [comment] 2019-01-08 09:12
I’m sorry but I don’t understand the issue. Is an exception being thrown? What isn’t working correctly? Can you please provide more information or show some code that will reproduce your problem?

**Comment by HongSic** [comment] 2019-01-08 10:07
FileStream fs = new FileStream("D:\\test.raw", FileMode.Create);
            WebRequest webRequest = (HttpWebRequest)WebRequest.Create("http://theprodigy.ru:8000/live.ogg");
            WebResponse resp = webRequest.GetResponse();
            VorbisReader vorbis = new VorbisReader(resp.GetResponseStream(), true); //System.NotSupportedException

            long testlen = 0;
            while (testlen < 100000)
            {
                float[] buf = new float[1024];
                int len = vorbis.ReadSamples(buf, 0, buf.Length);
                for (int i = 0; i < len; i++)
                {
                    byte[] four = BitConverter.GetBytes(buf[i]);
                    fs.Write(four, 0, 4);
                }

                fs.Flush();
            }

**Comment by HongSic** [comment] 2019-01-08 10:08
Added the code.

**Comment by HongSic** [comment] 2019-01-08 11:32
`
      using NVorbis;
      using NAudio.Wave;
      using System;
      using System.IO;
      using System.Net;
      
      namespace Test
      {
      
          public class StreamingTest
          {
              public static void main()
              {
                  NAudioStreamingTest_1(); //NotSupportException
                  NAudioStreamingTest_2(); //OK
                  NVobrisStreamingTest_1(); //NotSupportException
                  NVobrisStreamingTest_2(); //Invlid OGG file!!
              }
      
              public static void NAudioStreamingTest_1()
              {
                  WebRequest webRequest = (HttpWebRequest)WebRequest.Create("http://185.33.21.112/classical_128");
                  WebResponse resp = webRequest.GetResponse();
                  
                  NAudioWriteStream(resp.GetResponseStream()); //NotSupportException
      
                  resp.Close();
      
              }
              public static void NAudioStreamingTest_2()
              {
                  WebRequest webRequest = (HttpWebRequest)WebRequest.Create("http://185.33.21.112/classical_128");//http://theprodigy.ru:8000/live.ogg
                  WebResponse resp = webRequest.GetResponse();
      
                  var readFullyStream = new ReadFullyStream(resp.GetResponseStream());
                  NAudioWriteStream(readFullyStream); //OK
                  resp.Close();
              }
              public static void NVobrisStreamingTest_1()
              {
                  WebRequest webRequest = (HttpWebRequest)WebRequest.Create("http://theprodigy.ru:8000/live.ogg");
                  WebResponse resp = webRequest.GetResponse();
      
                  var readFullyStream = new ReadFullyStream(resp.GetResponseStream());
                  NVorbisWriteStream(resp.GetResponseStream()); //Invalid OGG File!!
                  resp.Close();
              }
              public static void NVobrisStreamingTest_2()
              {
                  WebRequest webRequest = (HttpWebRequest)WebRequest.Create("http://theprodigy.ru:8000/live.ogg");
                  WebResponse resp = webRequest.GetResponse();
      
                  NVorbisWriteStream(resp.GetResponseStream()); //System.NotSupportedException
                  resp.Close();
              }
      
              public static void NAudioWriteStream(Stream stream)
        {
            FileStream fs = new FileStream("D:\\test.raw", FileMode.Create);
            AcmMp3FrameDecompressor decompressor = new AcmMp3FrameDecompressor(new WaveFormat(44100, 2, 16));
            byte[] buffer = new byte[1024 * 500];
            using (stream)
            {
                long testlen = 0;
                while (testlen < 100000)
                {
                    Mp3Frame frame = Mp3Frame.LoadFromStream(stream); 
                    int decompressed = decompressor.DecompressFrame(frame, buffer, 0);
                    fs.Write(buffer, 0, decompressed);
                }
            }
            decompressor.Dispose();
            fs.Close();
        }
              public static void NVorbisWriteStream(Stream stream)
              {
                  VorbisReader vorbis = new VorbisReader(stream, true); //System.NotSupportedException
                  FileStream fs = new FileStream("D:\\test.raw", FileMode.Create);
      
                  long testlen = 0;
                  while (testlen < 100000)
                  {
                      float[] buf = new float[1024];
                      int len = vorbis.ReadSamples(buf, 0, buf.Length);
                      for (int i = 0; i < len; i++)
                      {
                          byte[] four = BitConverter.GetBytes(buf[i]);
                          fs.Write(four, 0, 4);
                      }
      
                      fs.Flush();
                  }
              }
          }
          public class ReadFullyStream : Stream
          {
              private readonly Stream sourceStream;
              private long pos; // psuedo-position
              private readonly byte[] readAheadBuffer;
              private int readAheadLength;
              private int readAheadOffset;
      
              public ReadFullyStream(Stream sourceStream)
              {
                  this.sourceStream = sourceStream;
                  readAheadBuffer = new byte[4096];
              }
              public override bool CanRead
              {
                  get { return true; }
              }
      
              public override bool CanSeek
              {
                  get { return false; }
              }
      
              public override bool CanWrite
              {
                  get { return false; }
              }
      
              public override void Flush()
              {
                  throw new InvalidOperationException();
              }
      
              public override long Length
              {
                  get { return pos; }
              }
      
              public override long Position
              {
                  get
                  {
                      return pos;
                  }
                  set
                  {
                      throw new InvalidOperationException();
                  }
              }
      
      
              public override int Read(byte[] buffer, int offset, int count)
              {
                  int bytesRead = 0;
                  while (bytesRead < count)
                  {
                      int readAheadAvailableBytes = readAheadLength - readAheadOffset;
                      int bytesRequired = count - bytesRead;
                      if (readAheadAvailableBytes > 0)
                      {
                          int toCopy = Math.Min(readAheadAvailableBytes, bytesRequired);
                          Array.Copy(readAheadBuffer, readAheadOffset, buffer, offset + bytesRead, toCopy);
                          bytesRead += toCopy;
                          readAheadOffset += toCopy;
                      }
                      else
                      {
                          readAheadOffset = 0;
                          readAheadLength = sourceStream.Read(readAheadBuffer, 0, readAheadBuffer.Length);
                          //Debug.WriteLine(String.Format("Read {0} bytes (requested {1})", readAheadLength, readAheadBuffer.Length));
                          if (readAheadLength == 0)
                          {
                              break;
                          }
                      }
                  }
                  pos += bytesRead;
                  return bytesRead;
              }
      
              public override long Seek(long offset, SeekOrigin origin)
              {
                  throw new InvalidOperationException();
              }
      
              public override void SetLength(long value)
              {
                  throw new InvalidOperationException();
              }
      
              public override void Write(byte[] buffer, int offset, int count)
              {
                  throw new InvalidOperationException();
              }
          }
      }

`

**Comment by ToddBertaOldham** [comment] 2019-01-08 12:03
In your code you are still using the response stream.
`
NVorbisWriteStream(resp.GetResponseStream()); //Invalid OGG File!!
`
You never use the stream in which the whole file is read. So NVorbis test 1 and 2 should have the same result.

**Comment by HongSic** [comment] 2019-01-08 12:40
so, Is there a way to solve this issue?

**Comment by ToddBertaOldham** [comment] 2019-01-08 21:17
Did you fix the test so that it will use the proper stream and then you still got an error? The test code should look like this:
```
   
var readFullyStream = new ReadFullyStream(resp.GetResponseStream());
NVorbisWriteStream(readFullyStream); //Invalid OGG File!!
   
```
Not this:
```
   
var readFullyStream = new ReadFullyStream(resp.GetResponseStream());
NVorbisWriteStream(resp.GetResponseStream()); //Invalid OGG File!!
   
```
If you did and are still getting an error, then please post the stack trace from the crash. It will likely give me enough information to know what is going wrong.

**Comment by HongSic** [comment] 2019-01-08 23:39
Thanks, wait

**Comment by HongSic** [comment] 2019-01-09 00:14
![image](https://user-images.githubusercontent.com/18072231/50866783-cc2a9e00-13ee-11e9-87d6-352b69c0e1da.png)

OGG Raw data
[OGG_raw_765KB.zip](https://github.com/ioctlLR/NVorbis/files/2738862/OGG_dump_765KB.zip)

**Comment by ToddBertaOldham** [comment] 2019-01-09 01:02
Something is wrong with the ogg file you attached. I opened it in four different media programs and they all skipped the first 8-9 seconds. Two of those programs gave me an error.

**Comment by HongSic** [comment] 2019-01-09 01:43
OGG Raw data is dumped network buffer. (http://theprodigy.ru:8000/live.ogg)

Here, part of dump code.
`
            while (filestream.Length <= 765500)
            {
                byte[] buf = new byte[10];
                webstream.Read(buf, 0, buf.Length);
                filestream.Write(buf, 0, buf.Length);
                Stream.Flush();
            }
`

so, I will try another OGG URL.

**Comment by ToddBertaOldham** [comment] 2019-01-09 01:57
Why are you checking the length of the file stream? It seems like you're just cutting it off. If you [download the whole file](https://docs.microsoft.com/en-us/dotnet/api/system.net.webclient.downloaddata?view=netframework-4.7) and then use it does it work?

**Comment by HongSic** [comment] 2019-01-09 02:23
Because this stream does not have an end.

I'll try WebClient
`

using NVorbis;
using System;
using System.IO;
using System.Net;

namespace StreamTest
{
    public class StreamingTest
    {
        public static void Main(string[] args)
        {
            NVobrisStreamingTest_WebClient1(); //Invalid OGG File!!
            NVobrisStreamingTest_WebClient2(); //(Attached ogg file)
[test.zip](https://github.com/ioctlLR/NVorbis/files/2739111/test.zip)


        }

        public static void NVobrisStreamingTest_1()
        {
            WebRequest webRequest = (HttpWebRequest)WebRequest.Create("http://theprodigy.ru:8000/live.ogg");
            WebResponse resp = webRequest.GetResponse();

            var readFullyStream = new ReadFullyStream(resp.GetResponseStream());
            NVorbisWriteStream(readFullyStream); //Invalid OGG File!!
            resp.Close();
        }
        public static void NVobrisStreamingTest_WebClient1()
        {
            WebClient client = new WebClient();
            Stream stream = client.OpenRead("http://theprodigy.ru:8000/live.ogg");
            var readFullyStream = new ReadFullyStream(stream);
            NVorbisWriteStream(readFullyStream); //Invalid OGG File!!
        }
        public static void NVobrisStreamingTest_WebClient2() //(Attached ogg file)
        {
            WebClient client = new WebClient();
            client.DownloadFile("http://theprodigy.ru:8000/live.ogg", "D:\\test.ogg");
        }
        public static void NVorbisWriteStream(Stream stream)
        {
            VorbisReader vorbis = new VorbisReader(stream, true); //System.NotSupportedException
            FileStream fs = new FileStream("D:\\test.raw", FileMode.Create);

            long testlen = 0;
            while (testlen < 100000)
            {
                float[] buf = new float[1024];
                int len = vorbis.ReadSamples(buf, 0, buf.Length);
                for (int i = 0; i < len; i++)
                {
                    byte[] four = BitConverter.GetBytes(buf[i]);
                    fs.Write(four, 0, 4);
                }

                fs.Flush();
            }
        }

    }
    public class ReadFullyStream : Stream
    {
        private readonly Stream sourceStream;
        private long pos; // psuedo-position
        private readonly byte[] readAheadBuffer;
        private int readAheadLength;
        private int readAheadOffset;

        public ReadFullyStream(Stream sourceStream)
        {
            this.sourceStream = sourceStream;
            readAheadBuffer = new byte[4096];
        }
        public override bool CanRead
        {
            get { return true; }
        }

        public override bool CanSeek
        {
            get { return true; }
        }

        public override bool CanWrite
        {
            get { return false; }
        }

        public override void Flush()
        {
            throw new InvalidOperationException();
        }

        public override long Length
        {
            get { return pos; }
        }

        public override long Position
        {
            get
            {
                return pos;
            }
            set
            {
                throw new InvalidOperationException();
            }
        }


        public override int Read(byte[] buffer, int offset, int count)
        {
            int bytesRead = 0;
            while (bytesRead < count)
            {
                int readAheadAvailableBytes = readAheadLength - readAheadOffset;
                int bytesRequired = count - bytesRead;
                if (readAheadAvailableBytes > 0)
                {
                    int toCopy = Math.Min(readAheadAvailableBytes, bytesRequired);
                    Array.Copy(readAheadBuffer, readAheadOffset, buffer, offset + bytesRead, toCopy);
                    bytesRead += toCopy;
                    readAheadOffset += toCopy;
                }
                else
                {
                    readAheadOffset = 0;
                    readAheadLength = sourceStream.Read(readAheadBuffer, 0, readAheadBuffer.Length);
                    //Debug.WriteLine(String.Format("Read {0} bytes (requested {1})", readAheadLength, readAheadBuffer.Length));
                    if (readAheadLength == 0)
                    {
                        break;
                    }
                }
            }
            pos += bytesRead;
            return bytesRead;
        }

        public override long Seek(long offset, SeekOrigin origin)
        {
            throw new InvalidOperationException();
        }

        public override void SetLength(long value)
        {
            throw new InvalidOperationException();
        }

        public override void Write(byte[] buffer, int offset, int count)
        {
            throw new InvalidOperationException();
        }
    }
}

`

ps. There is no error when playing a partial download of a file.
[StreamTest_src.zip](https://github.com/ioctlLR/NVorbis/files/2739113/StreamTest_src.zip)

**Comment by ToddBertaOldham** [comment] 2019-01-09 03:59
NVorbis does [support streaming](https://github.com/ioctlLR/NVorbis/blob/master/OpenTKSupport/OggStream.cs) however you need a proper stream with seeking to do it. I’m aware that the header is being downloaded but [identification is more complex than that](https://github.com/ioctlLR/NVorbis/blob/master/NVorbis/Ogg/OggContainerReader.cs) and decoding and [streaming an ogg file is more complex than you think](https://stackoverflow.com/a/25287011/7723843). Throwing a random segment of data at the decoder is going to cause issues. The media players are being extremely forgiving. I know that streaming an ogg file over a network is possible.

**Comment by HongSic** [comment] 2019-01-09 11:09
I think this stream is checking all OGG packet.

**Comment by ioctlLR** [comment] 2019-01-09 12:40
NVorbis does not support streaming like that.  The capability to read a non-seekable stream was a start, but it only works for streams where the headers are sent first (i.e., you're downloading a file OR the streaming server is smart enough to always send the header pages first).

There is a proposed standard for RTP streaming of Vorbis (https://xiph.org/vorbis/doc/rfc5215.txt) if someone wants to implement support, but I don't know whether doing so will actually help you.

You could always fork NVorbis, add support for your stream format to it, and send us a pull request...

**Comment by ToddBertaOldham** [comment] 2019-01-09 22:09
Interesting I had no idea that NVorbis supported non-seekable streams. Thank you for clearing things up ioctlLR. Sorry about that. While I don’t have the time to work on the network stream format with you HongSic I’d be happy to work with you during the process of merging it into NVorbis.

**Comment by ioctlLR** [comment] 2019-12-17 14:36
Looks like there is a bug with the non-seeking stream logic.  I'm going to split this issue into two new ones: One to remove the stream buffering logic, and one to add RTSP streaming support.
Closing this one.

**Closed by ioctlLR** 2019-12-17 14:36 UTC
Labels: enhancement
